let score1,score2,score3;
score1 = 29;
score2 = 30;
score3 = 36;
let totalScore = score1 + score2 + score3;
let avarageScore = totalScore / 3;
console.log(totalScore);
console.log(avarageScore);
let plates = 20;
let people = 7;
let remainingPlates = plates % people;
remainingPlates++;
console.log("There are " + remainingPlates + " plates avaiable");
